#ifndef BITTORRENT_CLIENT_TEST_PARSING_H
#define BITTORRENT_CLIENT_TEST_PARSING_H

// decode_announce_list tests
void test_decode_announce_list_valid_single_tracker(void);
void test_decode_announce_list_valid_multiple_trackers(void);
void test_decode_announce_list_valid_multiple_urls_per_tier(void);
void test_decode_announce_list_valid_empty_list(void);
void test_decode_announce_list_valid_nested_empty_lists(void);
void test_decode_announce_list_null_index_pointer(void);
void test_decode_announce_list_invalid_format_no_list(void);
void test_decode_announce_list_invalid_format_unclosed(void);
void test_decode_announce_list_invalid_format_malformed_inner(void);
void test_decode_announce_list_valid_index_tracking(void);
void test_decode_announce_list_valid_udp_tracker(void);
void test_decode_announce_list_valid_mixed_protocols(void);
void test_decode_announce_list_logging_modes(void);

// read_info_files single file tests
void test_read_info_files_single_file_valid_simple(void);
void test_read_info_files_single_file_valid_large_file(void);
void test_read_info_files_single_file_valid_zero_length(void);
void test_read_info_files_single_file_null_index(void);
void test_read_info_files_single_file_invalid_no_length(void);
void test_read_info_files_single_file_invalid_no_name(void);
void test_read_info_files_single_file_invalid_malformed(void);
void test_read_info_files_single_file_index_tracking(void);

// read_info_files multiple files tests
void test_read_info_files_multiple_files_valid_two_files(void);
void test_read_info_files_multiple_files_valid_single_file(void);
void test_read_info_files_multiple_files_valid_nested_path(void);
void test_read_info_files_multiple_files_valid_deep_nesting(void);
void test_read_info_files_multiple_files_valid_empty_files_list(void);
void test_read_info_files_multiple_files_valid_many_files(void);
void test_read_info_files_multiple_files_null_index(void);
void test_read_info_files_multiple_files_invalid_no_files_key(void);
void test_read_info_files_multiple_files_invalid_no_length(void);
void test_read_info_files_multiple_files_invalid_no_path(void);
void test_read_info_files_multiple_files_invalid_malformed(void);
void test_read_info_files_multiple_files_index_tracking(void);

// Edge case tests
void test_read_info_files_edge_case_very_long_filename(void);
void test_read_info_files_edge_case_special_chars_in_name(void);
void test_read_info_files_edge_case_max_uint64_length(void);

// Logging mode tests
void test_read_info_files_logging_modes_single(void);
void test_read_info_files_logging_modes_multiple(void);

// Integration tests
void test_integration_announce_list_complex_structure(void);
void test_integration_files_list_mixed_sizes(void);

#endif // BITTORRENT_CLIENT_TEST_PARSING_H